version: '2'

services:
  proxy:
    build: nginx/
    container_name: "portainer-proxy"
    ports:
      - "80:80"
    networks:
      - local

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
    - "PMA_ABSOLUTE_URI=http://dev.smartid.my/phpmyadmin"
    volumes:
    - "./phpmyadmin/sessions:/sessions"
    networks:
      - local
    expose:
      - "80"

  omnidb:
    image: taivokasper/omnidb
    container_name: omnidb
    restart: always
    volumes:
      - ./config-omnidb:/etc/omnidb
    networks:
      - local
    expose:
      - "8080"

networks:
  local:
    driver: bridge
